# Generated by Django 3.1.2 on 2020-10-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_auto_20201017_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
