# Generated by Django 3.1.2 on 2020-10-26 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_auto_20201018_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=None, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Phone no must be entered in format: Up to 10 digits allowed.', regex='^\\ ?1?\\d{9,15}$')]),
        ),
    ]
