# Generated by Django 3.1.2 on 2020-10-26 13:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_auto_20201026_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.CharField(default=None, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Pincode must be entered in format: Up to 6 digits allowed.', regex='^\\ ?1?\\d{9,15}$')]),
        ),
    ]
