# Generated by Django 3.1.3 on 2020-11-04 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_auto_20201026_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='author_profile/default.jpeg', upload_to='author_profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pincode',
            field=models.CharField(default=None, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Pincode must be entered in format: Up to 6 digits allowed.', regex='^[1-9][0-9]{5}$')]),
        ),
    ]
