# Generated by Django 3.1.2 on 2020-11-03 12:57

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20201028_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pdf',
            field=models.FileField(default='sample.pdf', upload_to='content', validators=[content.validators.validate_file_extension]),
        ),
    ]
