# Generated by Django 3.1.3 on 2020-11-04 12:28

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20201103_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pdf',
            field=models.FileField(default='content/sample.pdf', upload_to='content', validators=[content.validators.validate_file_extension]),
        ),
    ]
