# Generated by Django 3.1.3 on 2020-11-04 13:40

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20201104_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pdf',
            field=models.FileField(upload_to='content', validators=[content.validators.validate_file_extension]),
        ),
    ]
