# Generated by Django 3.1.3 on 2020-11-05 14:45

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20201104_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='likes',
        ),
        migrations.AlterField(
            model_name='content',
            name='pdf',
            field=models.FileField(upload_to='content_pdf', validators=[content.validators.validate_file_extension]),
        ),
    ]
