# Generated by Django 3.1.3 on 2020-11-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_auto_20201105_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='content',
            name='summary',
            field=models.CharField(max_length=60),
        ),
    ]
