# Generated by Django 3.1.3 on 2020-11-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20201108_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='content',
            name='summary',
            field=models.TextField(max_length=60),
        ),
    ]
